### ISSUE TITLE
[Wiki] 사용자 메뉴얼 페이지 및 로드맵 작성 

### ISSUE THREAD

**Issue by dhgudehd98** [ssg-java3-240304/up-and-down#168]
## 🌈 Success criteria
- 사용자 메뉴얼 페이지를 통해서 사용자가 웹 서비스의 주요 기능과 사용 방법을 쉽게 이해할 수 있다.
- 로드맵을 통해서 현재 상태와 미래에 개선해야 될 부분을 작성함으로써 보다 프로젝트의 완성도를 높일 수 있다.

## 👷To-do
- [x] 프로젝트 및 팀원 소개 
- [x] 프로젝트 기능 소개 
- [x] 기능별 사용자 메뉴얼 작성 
- [x] 로드맵 작성
