### ISSUE TITLE
[PPT] PPT 제작

### ISSUE THREAD

**Issue by subkka** [ssg-java3-240304/up-and-down#170]
## 🌈 Success criteria
1. 프로젝트에 대한 발표 내용을 구성 및 제작합니다.

## 👷To-do
- [x] ppt 템플릿 선정
- [x] 시나리오 적용
- [x] 작업 문서 삽입
- [x] 시연 영상 삽입
