### ISSUE TITLE
[회원가입] 회원가입 페이지 퍼블리싱 작업

### ISSUE THREAD

**Issue by subkka** [ssg-java3-240304/up-and-down#30]
## 🌈 Success criteria

1. 회원가입은 약관동의 ,정보입력, 계정생성, 완료 순으로 진행됩니다.
2. 약관동의 스탭에서 미동의 시 회원가입할 수 없습니다.
3. 정보입력 스탭에서 개인 정보 입력 후 전화번호 인증을 받아야합니다.
4. 계정생성 스탭에서 아이디 중복, 비밀번호 이중 확인을 거쳐야 합니다.
5. 회원가입이 완료되면 로그인할 수 있습니다.

## 👷To-do
- [x] 약관동의 페이지 퍼블리싱
- [x] 정보입력 페이지 퍼블리싱
- [x] 계정생성 페이지 퍼블리싱
- [x] 완료 페이지 퍼블리싱
