### ISSUE TITLE
[회원가입] 회원가입 페이지 기능 구현

### ISSUE THREAD

**Issue by subkka** [ssg-java3-240304/up-and-down#31]
## 🌈 Success criteria

1. 회원가입은 약관동의 ,정보입력, 계정생성, 완료 순으로 진행됩니다.
2. 약관동의 스탭에서 미동의 시 회원가입할 수 없습니다.
3. 정보입력 스탭에서 개인 정보 입력 후 전화번호 인증을 받아야합니다.
4. 계정생성 스탭에서 아이디 중복, 비밀번호 이중 확인을 거쳐야 합니다.
5. 회원가입이 완료되면 로그인할 수 있습니다.

## 👷To-do
- [x] 약관동의 페이지 기능 구현
- [x] 정보입력 페이지 기능 구현
- [x] 계정생성 페이지 기능 구현
- [x] 완료 페이지 기능 구현

## 💫ISSUES
- 🔴 SMS API 비동기 요청으로 보내는데 login으로 redirect되던 문제
- 🟢 요청받는 Controller에서 데이터를 반환해야 하기 때문에 viewName으로 혼동하지 않도록 @ResponseBody 또는 ResponseEntity를 사용해야 한다!
![Image](https://github.com/user-attachments/assets/ce88cd03-615d-4490-8d0c-e4c57da2fd36)
