### ISSUE TITLE
[메인페이지] 페이지 퍼블리싱

### ISSUE THREAD

**Issue by KimYeonChan34** [ssg-java3-240304/up-and-down#49]
## 🌈 Success criteria
1. 본문에 to-do 항목이 노출되어야 한다.

## 👷To-do
- [x] 광고 베너
- [x] 패키지 여행 검색창
- [x] 실시간 최다 검색 상품 목록
- [x] 테마별 상품 목록
