### ISSUE TITLE
[커뮤니티] 메인페이지 기능 구현

### ISSUE THREAD

**Issue by jeonhyeonseon** [ssg-java3-240304/up-and-down#59]
## 🌈 Success criteria
1. 회원, 비회원은 채팅방 목록을 확인할 수 있습니다.
2. 회원, 비회원은 채팅방을 검색할 수 있습니다.
3. 제목, 제목 + 내용, 카테고리를 통해 검색할 수 있습니다.
4. 비회원은 채팅방 [만들기] 버튼 클릭시 로그인 페이지로 이동합니다.

## 👷To-do
- [ ] 전체 목록 조회
- [ ] [우리모임]에 해당하는 목록 조회
- [ ] [내모임]에 해당하는 목록 조회
- [ ] 제목, 제목+내용에 해당하는 목록 조회
- [ ] 해당 카테고리의 목록 조회
