### ISSUE TITLE
[데이터] 데이터를 주기적으로 가져올 수 있습니다.

### ISSUE THREAD

**Issue by dhgudehd98** [ssg-java3-240304/up-and-down#84]
## :🌈: Success criteria
1. Spring - scheduler를 설정해서 주기적으로 데이터를 가져옵니다.
2. 주기를 짧게 설정해서 데이터를 크롤링 하는지 테스트합니다.
3. 데이터 크롤링 할 수행할 서버를 준비하고, 연결되는지 확인합니다.
## :👷:To-do

- [x] Spring-scheduler 의존성 및 scheduler 설정 
- [x] Scheduler를 짧은 주기로 설정하여 콘솔 로그를 통해 정상 작동하는지 확인 
- [x] 크롤링 된 데이터가 예상대로 저장되는지 Test
- [x] 배포 환경에서 서버 구축 및 환경 설정 
- [x] 자동화 테스트 : 1일 주기로 자동으로 데이터가 크롤링되고 저장되는지 테스트
